version: '3'
services:

  frontend:
    build: ./fe
    container_name: fe_green
    ports:
      - "8020:80"         # port 80 nginx di dalam, ke 8080 di luar
    depends_on:
      - backend
    networks:
      - app_net

  backend:
    build: ./be
    container_name: be_green
    ports:
      - "3020:3020"       # backend diakses lewat 3000
    environment:
      - DB_HOST=db        # kasih tau backend, host DB itu 'db'
      - DB_USER=root
      - DB_PASSWORD=testing123
      - DB_NAME=testdb
    depends_on:
      - db
    restart: always
    networks:
      - app_net

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testing123
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
