version: '3'
services:
  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile
    ports:
      - "8020:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./be
      dockerfile: dockerfile
    ports:
      - "3020:3020"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
