# Gunakan image nginx
FROM nginx:alpine

# Hapus config default nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copy file konfigurasi nginx buatan sendiri
COPY nginx.conf /etc/nginx/conf.d

# Copy semua file frontend (HTML, CSS, JS) ke direktori nginx
COPY . /usr/share/nginx/html
